// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const SAKANA_MODELS = {
		"fugu": {
			id: "fugu",
			name: "Fugu",
			api: "openai-completions",
			provider: "sakana",
			baseUrl: "https://api.sakana.ai/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 0,
				output: 0,
				cacheRead: 0,
				cacheWrite: 0,
			},
			contextWindow: 1000000,
			maxTokens: 128000,
		} satisfies Model<"openai-completions">,
		"fugu-ultra": {
			id: "fugu-ultra",
			name: "Fugu Ultra",
			api: "openai-completions",
			provider: "sakana",
			baseUrl: "https://api.sakana.ai/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: {
				input: 5,
				output: 30,
				cacheRead: 0.5,
				cacheWrite: 0,
			},
			contextWindow: 272000,
			maxTokens: 128000,
		} satisfies Model<"openai-completions">
} as const;
